### ISSUE TITLE
[Question] why activityModule() is depreciated?

### ISSUE THREAD

**Issue by sagar15795** [MindorksOpenSource/android-dagger2-example#3]
In mainactivity.java
```
    public ActivityComponent getActivityComponent() {
        if (activityComponent == null) {
            activityComponent = DaggerActivityComponent.builder()
                    .activityModule(new ActivityModule(this))
                    .applicationComponent(DemoApplication.get(this).getComponent())
                    .build();
        }
        return activityComponent;
    }
```

I am getting depreciate error on line no-30 i.e.  `.activityModule(new ActivityModule(this))`.

If you could explain me why is it happening then it will be helpful?

**Comment by amitshekhariitbhu** [comment]
@sagar15795 : Google has depreciated it. Check by clicking on that function.

**Comment by sagar15795** [comment]
Yes, that I also know but I don't get the clear reason why is it depreciated and how to remove it? Sorry if it is a silly question because I am a beginner to Dagger 2.

**Comment by amitshekhariitbhu** [comment]
This is deprecated because new updated Dagger 2 can handle it automatically.

**Comment by sagar15795** [comment]
So we don't need to add it now

**Comment by janishar** [comment]
@sagar15795 
This deprecation is shown because Dagger2 has found that the ActivityModule do not provide any dependency and is redundant. The application will run the same way even if you remove the module ( i.e. remove this line: .activityModule(new ActivityModule(this))). If you add a provides method in the ActivityModule and inject that dependency somewhere then this deprecation will be removed because then it will be a requirement for DI.

**Comment by sagar15795** [comment]
@janishar 
Thanks for the explanation.
